### ISSUE TITLE
Wrong filename of pycis.model.instrument

### ISSUE THREAD

**Issue by ssilburn** [jsallcock/pycis#1]
The filename of pycis/model/Instrument.py starts with an uppercase 'I' but in the code the module is referred to as 'instrument' with a lowercase 'i'. This causes an exception when trying to import pycis.model: "ImportError: No module named 'pycis.model.instrument'". Fixed in my local copy by renaming the file with a lowercase i.

**Comment by jsallcock** [comment]
Fixed by renaming instrument.py
